name: End-to-end tests
on:
  pull_request:
  push:
    branches:
      - master
      - development
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://10.1.0.4/'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
