name: Cypress smoke test
on:
  pull_request:
  push:
    branches:
      - master
      - development
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        continue-on-error: true
        
      - name: Update dependencies
        run: yarn install

      - name: Increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      
      #- name: Build web application
      #  run: yarn start
        
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          parallel: true
          start: yarn start
          run: npx cypress run
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://10.1.0.4/'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
