name: Cypress smoke test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        continue-on-error: true
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120